"""empty message

Revision ID: 0c44cd2b3657
Revises: 8e2f38ff2340
Create Date: 2025-07-31 14:27:09.713208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c44cd2b3657'
down_revision: Union[str, Sequence[str], None] = '8e2f38ff2340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versamenti', sa.Column('tipo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('versamenti', 'tipo')
    # ### end Alembic commands ###
