"""empty message

Revision ID: 1f3484443fde
Revises: fcfc58581e96
Create Date: 2026-03-08 12:29:15.131999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3484443fde'
down_revision: Union[str, Sequence[str], None] = 'fcfc58581e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versamenti', sa.Column('invoice_id', sa.BigInteger(), nullable=False))
    op.add_column('versamenti', sa.Column('valuta', sa.String(), nullable=True))
    op.add_column('versamenti', sa.Column('stato', sa.String(), nullable=True))
    op.add_column('versamenti', sa.Column('data_pagamento', sa.DateTime(), nullable=True))
    op.alter_column('versamenti', 'importo',
               existing_type=sa.INTEGER(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'versamenti', ['invoice_id'])
    op.drop_column('versamenti', 'tipo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('versamenti', sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'versamenti', type_='unique')
    op.alter_column('versamenti', 'importo',
               existing_type=sa.REAL(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('versamenti', 'data_pagamento')
    op.drop_column('versamenti', 'stato')
    op.drop_column('versamenti', 'valuta')
    op.drop_column('versamenti', 'invoice_id')
    # ### end Alembic commands ###
