"""update v1.1

Revision ID: 29881d991df2
Revises: 87c9758b6cb8
Create Date: 2026-05-06 17:29:04.729018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29881d991df2'
down_revision: Union[str, Sequence[str], None] = '87c9758b6cb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('giocate_demo', sa.Column('round_id', sa.String(), nullable=True))
    op.add_column('giocate_real', sa.Column('round_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('giocate_real', 'round_id')
    op.drop_column('giocate_demo', 'round_id')
    # ### end Alembic commands ###
