"""aggiunte tabelle giocate_real e demo

Revision ID: 3f06713c3006
Revises: ac469aa57bf2
Create Date: 2026-05-04 20:57:28.499272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f06713c3006'
down_revision: Union[str, Sequence[str], None] = 'ac469aa57bf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('giocate_demo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('puntata', sa.REAL(), nullable=True),
    sa.Column('vincita', sa.REAL(), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('giocate_real',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('puntata', sa.REAL(), nullable=True),
    sa.Column('vincita', sa.REAL(), nullable=True),
    sa.Column('data', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('giocate_real')
    op.drop_table('giocate_demo')
    # ### end Alembic commands ###
