"""empty message

Revision ID: 5aefbecebecd
Revises: 3f0ff5597e0c
Create Date: 2025-06-29 15:17:32.063001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5aefbecebecd'
down_revision: Union[str, Sequence[str], None] = '3f0ff5597e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('demo_balance', sa.REAL(), nullable=True))
    op.drop_column('User', 'n_card')
    op.drop_column('User', 'pay_pal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('pay_pal', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('User', sa.Column('n_card', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'demo_balance')
    # ### end Alembic commands ###
